name: Continuous Integration and Continuous Deployment
run-name: ${{ github.actor }} submitted a CI CD Action
on:
  push:
    branches: [ "main" ]

jobs:
  Explore-GitHub-Actions:
    if: contains(github.event.head_commit.message, '/run-')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comment ${{ github.event.head_commit.message }}"
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: Install dependencies
        run: |
          pip install requests kubernetes
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker # --quiet #authenticate to gcr
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build API Service Container 
        run: |-
          cd ${{ github.workspace }}/src/api-service/
          docker build -t instacap-service -f Dockerfile .
      - name: Build Frontend Container 
        run: |-
          cd ${{ github.workspace }}/src/frontend-react/
          docker build -t instacap-frontend -f Dockerfile .
      - run: echo "Job's status is ${{ job.status }}."
      - name: Run Deploy App
        if: contains(github.event.head_commit.message, '/run-deploy-app')
        run: |-
          docker run --rm --name ansible-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.ssh:/home/app/.ssh \
            -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            --volume $GITHUB_WORKSPACE:/workspace \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            --env GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-project-398320 \
            -e GCP_ZONE=us-central1-a \
            ansible-deployment sh deploy-app.sh

          
         